import os
import logging
import pandas as pd

logger = logging.getLogger("vesper_automator")

class FileFinisher:
    def __init__(self, processed_root):
        """
        Initialize with the root folder where organized data should go.
        e.g., ./data/processed/
        """
        self.processed_root = processed_root
        self.structure = {
            "gps": os.path.join(processed_root, "gps"),
            "imu": os.path.join(processed_root, "imu"),
            "aud": os.path.join(processed_root, "aud")
        }
        
        # Create output directories if they don't exist
        for path in self.structure.values():
            os.makedirs(path, exist_ok=True)

    def get_device_id_from_txt(self, bin_filepath):
        """
        Parses the sidecar .txt log file (generated by parser) to find DeviceID.
        Returns 'UnknownTag' if not found.
        """
        # Assume .txt is in the same folder as the .BIN
        txt_path = os.path.splitext(bin_filepath)[0] + ".txt"
        
        if not os.path.exists(txt_path):
            return "UnknownTag"

        try:
            with open(txt_path, "r") as f:
                for line in f:
                    if line.startswith("DeviceID:"):
                        # Extract ID (e.g., "DeviceID:4764505D" -> "4764505D")
                        return line.split(":")[1].strip()
        except Exception as e:
            logger.warning(f"Could not read metadata from {txt_path}: {e}")
            
        return "UnknownTag"

    def save_imu_csv(self, dataframe, original_filepath, uid=None):
        """
        Saves the IMU DataFrame to CSV with a timestamped filename.
        
        Format: START_END_UID.csv
        Example: 20250929-073451_20250929-074500_4764505D.csv
        """
        if dataframe is None or dataframe.empty:
            logger.warning(f"Skipping save for {original_filepath}: DataFrame is empty.")
            return False

        #---Resolve Device ID (UID)---
        # If main.py didn't pass a specific UID, try to grab it from the .txt file
        if not uid or uid == "UnknownTag" or uid == "VesperTag":
            detected_id = self.get_device_id_from_txt(original_filepath)
            if detected_id != "UnknownTag":
                uid = detected_id

        output_path = None
        try:
            #---Extract Start and End times from the Data---
            # dataframe['Time'] contains datetime objects from the parser
            start_dt = dataframe['Time'].iloc[0]
            end_dt = dataframe['Time'].iloc[-1]
            
            # Format: YYYYMMDD-HHMMSS
            time_fmt = "%Y%m%d-%H%M%S"
            start_str = start_dt.strftime(time_fmt)
            end_str = end_dt.strftime(time_fmt)

            #---Construct Filename---
            # VesperApp style: Start_End_DeviceID.csv
            new_filename = f"{start_str}_{end_str}_{uid}.csv"
            output_path = os.path.join(self.structure["imu"], new_filename)

            #---Save to CSV---
            # Note: Using comma (,) as separator is standard for data analysis.
            # If you specifically need Semicolon for Excel in Europe, change sep=';'
            dataframe.to_csv(output_path, index=False, sep=',') 
            
            logger.info(f"Saved IMU CSV: {new_filename}")
            return True

        except Exception as e:
            logger.error(f"Failed to save CSV {output_path if output_path else 'Unknown'}: {e}")
            return False